### ISSUE TITLE
Twitter's video can't crawl, you're crawling the comment's video?

### ISSUE THREAD

**Issue by wang-weart** [altbdoor/tweet-media-archive#1]
Twitter's video can't crawl, you're crawling the comment's video?

**Comment by altbdoor** [comment]
Hi, sorry I think I used the wrong term. They are usually short GIFs.

As an example:
https://twitter.com/tkmiz/status/999732158141947904

```
$ python tweet_media_archive.py -u tkmiz --exclude_image --min_date="2018-05-23 00:00:00" --debug
2018-05-24 19:21:35, 999732158141947904, https://video.twimg.com/tweet_video/Dd_DFxSVQAA5qcR.mp4
2018-05-24 18:08:39, 999713803464916992, https://video.twimg.com/tweet_video/Dd-yY2CV0AAHWEx.mp4
```

Could you post an example of a Twitter video post so I can try to crawl it?

**Comment by altbdoor** [comment]
I have enhanced the code to be able to scrape the videos as well. It requires a browser though. Read more about it in the readme file.
